# Generated by Django 5.1.3 on 2024-11-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='modules/', verbose_name='Изображение'),
        ),
    ]
